# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'cs'
        
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones


    admin.okres:
        class: App\Admin\OkresAdmin
        arguments: [~, App\Entity\Okres, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Okresy  }


    admin.kraj:
        class: App\Admin\KrajAdmin
        arguments: [~, App\Entity\Kraj, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Kraje  }

    admin.typ_zarizeni:
        class: App\Admin\TypZarizeniAdmin
        arguments: [~, App\Entity\TypZarizeni, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Typy zařízení"  }

    admin.jazyk_vyuky:
        class: App\Admin\JazykVyukyAdmin
        arguments: [~, App\Entity\JazykVyuky, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Jazyky výuky"  }

    admin.zrizovatel:
        class: App\Admin\ZrizovatelAdmin
        arguments: [~, App\Entity\Zrizovatel, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Zřizovatelé zařízení"  }

    admin.reditelstvi:
        class: App\Admin\ReditelstviAdmin
        arguments: [~, App\Entity\Reditelstvi, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Ředitelství"  }

    admin.zarizeni:
        class: App\Admin\ZarizeniAdmin
        arguments: [~, App\Entity\Zarizeni, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Školní zařízení"  }

    admin.trida:
        class: App\Admin\TridaAdmin
        arguments: [~, App\Entity\Trida, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Třídy"  }

    admin.trida_vlastnosti:
        class: App\Admin\TridaVlastnostiAdmin
        arguments: [~, App\Entity\TridaVlastnosti, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Vlastnosti tříd"  }


    App\EntityListener\TridaListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    App\Service\RedIzoService:
        arguments:
            $file: '../skoly.json'

# TODO
#    App\AdminFilter\JsonListFilter:
#        tags:
#            - { name: sonata.admin.filter.type }
