sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

            -
                position: top
                class: col-xs-6 col-sm-3
                type: sonata.admin.block.stats
                settings:
                    code: admin.zarizeni
                    icon: fas fa-school
                    text: Zařízení
                    color: bg-yellow
                    filters:
                        aktivni: {value: true}

            -
                position: top
                class: col-xs-6 col-sm-3
                type: sonata.admin.block.stats
                settings:
                    code: admin.trida
                    icon: fas fa-chalkboard
                    text: Třídy
                    color: bg-blue
                    filters:
                        aktivni: {value: true}

            -
                position: top
                class: col-sm-12 col-md-12 col-12
                type: sonata.block.service.text
                settings:
                    content: >
                        <h2>Vítejte v reportu kapacit školských zařízení</h2>
                        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nullam eget nisl. Fusce consectetuer risus a nunc. Aliquam erat volutpat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam dictum tincidunt diam. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Integer rutrum, orci vestibulum ullamcorper ultricies, lacus quam ultricies odio, vitae placerat pede sem sit amet enim. Integer tempor. Mauris metus. Donec iaculis gravida nulla.

        groups: #main menu
            skoly:
                label: Školy a třídy
                icon: fas fa-school
                items:
                    - admin.zarizeni
                    - admin.trida
                    - admin.reditelstvi
            ciselniky:
                label: Číselníky
#                roles:        [ ROLE_ADMIN_ANNONCE ]
                icon: fas fa-table
                items:
                    - admin.okres
                    - admin.kraj
                    - admin.typ_zarizeni
                    - admin.jazyk_vyuky
                    - admin.trida_vlastnosti

#    options:
#        legacy_twig_text_extension: false

    show_mosaic_button: false

    templates:
        layout: '@SonataTranslation/standard_layout.html.twig'

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
