admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /report

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /report

admin_logout:
    path: /logout

sonata_translation:
    resource: '@SonataTranslationBundle/Resources/config/routes.yaml'